### ISSUE TITLE
Swift Package Manager not seeing Airship module 

### ISSUE THREAD

**Issue by twalshcbs** [urbanairship/ios-library#259]
# Preliminary Info

### What Airship dependencies are you using?
v14.1.2 

### What are the versions of any relevant development tools you are using?
 XCode Version 12.0.1 (12A7300) 

# Report

### What unexpected behavior are you seeing?
 Importing Airship it will not compile, say "No such module 'Airship'"

I made a sample project and tried to implement Airship and got the same error on the "Import Airship"

**Comment by marc-scig** [comment]
Hi @twalshcbs,

The way this package is currently written, the Airsihp library is actually a just a collection of modular library targets instead of a target of its own. So while `@import Airship` doesn't work, you should be able to import `AirshipCore`, `AirshipMessageCenter`, `AirshipAutomation` and `AirshipExtendedActions`, as needed. We're looking at tweaking the package definition for a future minor release, as there are clearly still a few kinks to iron out.

**Comment by twalshcbs** [comment]
I can't import AirshipCore or any other Airship library.  The auto-fill see none of them 
![Screen Shot 2020-10-06 at 5 13 49 AM](https://user-images.githubusercontent.com/61519030/95189098-03c8a480-0793-11eb-842d-295caa97254d.png)
![Screen Shot 2020-10-06 at 5 15 06 AM](https://user-images.githubusercontent.com/61519030/95189109-062afe80-0793-11eb-8dde-972e082d81fc.png)

**Comment by marc-scig** [comment]
@twalshcbs you shouldn't need to link both Airship and AirshipCore as libraries, as per your first screenshot. Airship contains AirshipCore, among others. Your second screenshot is showing a compiler error on the Airship import, which was the one I suggested you remove.

**Comment by gabehoffman** [comment]
@marc-scig - I'm not following your suggestion at all. I'm in the same place as @twalshcbs. 

I've successfully imported the Airship Package, but can't import anything.

Here's a really simple example file.

```swift
import AirshipExtensions

class NotificationService: UANotificationServiceExtension { }
```

That import doesn't compile. And not having the import doesn't work either. What's the correct way to make things happy now?

**Comment by gabehoffman** [comment]
@marc-scig - Here's a screen shot of what I'm seeing, I can't import any of the things you suggest (AirshipCore, AirshipMessageCenter, AirshipAutomation and AirshipExtendedActions). You can see the auto complete has nothing related to Airship in the list of options.

![Screen Shot 2020-11-16 at 3 34 29 PM](https://user-images.githubusercontent.com/2106257/99305044-3dc0a800-2821-11eb-9057-e6e00be8597b.png)

**Comment by gabehoffman** [comment]
So that file was in a different target, thus not having access to the framework. Go to your project settings, then to the target in question, then to the Frameworks and Libraries and add which ever framework you need. 

If you are having this issue, check that first.

Then if you want to double check, create new project try to import the Airship package there, it should be working fine to import something like `import AirshipCore`

It might be a little hard to figure out which import things map to in the SPM world but not too bad.

**Comment by ChuckMN** [comment]
Hello @marc-scig ,

Any update on changes to the SPM implementation to simplify the implementation?

I am still encountering the same issue as others (unable to import any modules) while implementing Airship using SPM. Do you have any work around suggestions that we could try leveraging while this is being worked on?

Thanks so much for the help!

**Comment by gabehoffman** [comment]
> Hello @marc-scig ,
> 
> Any update on changes to the SPM implementation to simplify the implementation?
> 
> I am still encountering the same issue as others (unable to import any modules) while implementing Airship using SPM. Do you have any work around suggestions that we could try leveraging while this is being worked on?
> 
> Thanks so much for the help!

I was able to get things working fine, by importing `https://github.com/urbanairship/ios-library`, and then making sure that the file I was attempting to import from, had the relevant Airship frameworks added. I think SPM does this for you on your main target, but it might not on any additional targets.

**Comment by marc-scig** [comment]
@gabehoffman, @ChuckMN apologies for not getting back to you sooner!

@ChuckMN if the above info doesn't help, something I can say from my own experience is that the SPM implementation in Xcode can sometimes do a poor job of autosuggesting imports, so the mere lack of a suggestion doesn't necessarily mean the package isn't there. In most of the failing examples here there's a misnamed import – for instance there is no AirshipExtensions SPM modules but there are modules named `AirshipNotificationContentExtension` and `AirshipNotificationServiceExtension`. These roughly follow the names of the package libraries added to your project, with the exception of Airship which is an umbrella library containing multiple targets.

Technically the module name you import in your code is a target, not the library you embedded. In most cases the library and target have the same name, but that's not guaranteed. For instance, in the Packge.swift, you can see that the Airship library bundles together several targets, each of which need to be imported individually even if you just embedded `Airship`.

```
    products: [
        .library( 
            name: "Airship",
            targets: ["AirshipCore", "AirshipAutomation", "AirshipMessageCenter", "AirshipExtendedActions"]),
        .library( 
            name: "AirshipCore",
            targets: ["AirshipCore"]),
        .library( 
            name: "AirshipAutomation",
            targets: ["AirshipAutomation"]),
        ...
``` 

I agree it's confusing, but it appears to be the way SPM works, for better or for worse. In the future we might consider reorganizing the package to make `Airship` it's own unique target, which would probably make things more intuitive.

**Comment by mjablonski-wh** [comment]
In case someone stumbles upon this thread, there is sort of a solution to this problem. There is a caveat though: it use an undocumented, nonetheless widely used, attribute called `@_exported`.

Assuming you have added Airship dependency:
```swift
dependencies: [
  ...
  .package(name: "Airship", url: "https://github.com/urbanairship/ios-library", .upToNextMajor(from: "16.0.0")),
]
```
Create a new target called `Airship`:

```swift
targets: [
  ...
  .target(name: "Airship", dependencies: [
    .product(name: "AirshipCore", package: "Airship"),
    .product(name: "AirshipAutomation", package: "Airship"),
    .product(name: "AirshipMessageCenter", package: "Airship"),
    ...
  ]),
]
```
Then create a single file called `Exported.swift`:
```swift
@_exported import AirshipCore
@_exported import AirshipAutomation
@_exported import AirshipMessageCenter
...
```

Thats it. You can now use Airship as dependency without the need of importing each libraries independently.
